In [8]:
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
df = pd.read_csv("HTRU_2.csv",header=None)

In [3]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=101)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [6]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200,min_samples_split=5,max_features=4,max_depth=110)
rfc.fit(X_train,y_train)

RandomForestClassifier(max_depth=110, max_features=4, min_samples_split=5,
                       n_estimators=200)

In [7]:
y_pred = rfc.predict(X_test)

In [25]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
#~92% TPR

[[4074   26]
 [  44  331]]


0.9843575418994414

In [27]:
cm[0][1]

26

In [18]:
predicted = rfc.predict_proba(X_test)

In [19]:
predicted = (predicted[:,1]>=.4).astype('int')

In [20]:
predicted

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
cm = confusion_matrix(y_test, predicted)
print(cm)
accuracy_score(y_test, predicted)

[[4065   35]
 [  41  334]]


0.9830167597765364

In [22]:
#1. make a list of valuers evenly spaced between 0 and 100
#2. make a for loop that iterates through the list
#3. For each iteration I need to collect the model accuracy, TPR, difference between them, and the value of the list

In [54]:
temp_list = [.05,.1,.15,.2,.25,.3,.35,.4,.45,.5,.55,.6,.65,.7,.75,.8,.85,.9,.95]
acc_lst = []
tpr_lst = []
diff_lst = []
thresh_lst = []
for thresh in temp_list:
    pred_prob = rfc.predict_proba(X_test)
    pred_prob = (pred_prob[:,1]>=thresh).astype('int')
    cm = confusion_matrix(y_test, pred_prob)
    acc_lst.append(accuracy_score(y_test, pred_prob))
    tpr_lst.append(cm[1][1]/(cm[1][1]+cm[0][1]))
    thresh_lst.append(thresh)

In [55]:
acc_lst

[0.9318435754189944,
 0.9629050279329608,
 0.972513966480447,
 0.9754189944134078,
 0.977877094972067,
 0.9801117318435755,
 0.9816759776536312,
 0.9830167597765364,
 0.9841340782122905,
 0.9843575418994414,
 0.9839106145251396,
 0.9832402234636871,
 0.9825698324022346,
 0.9825698324022346,
 0.9818994413407821,
 0.9818994413407821,
 0.9787709497206704,
 0.9756424581005586,
 0.9693854748603352]

In [56]:
tpr_lst

[0.5550314465408805,
 0.7172557172557172,
 0.7889908256880734,
 0.8177458033573142,
 0.8415841584158416,
 0.8685567010309279,
 0.8865435356200527,
 0.9051490514905149,
 0.919889502762431,
 0.927170868347339,
 0.9316239316239316,
 0.936046511627907,
 0.9406528189910979,
 0.9459459459459459,
 0.9537037037037037,
 0.9681528662420382,
 0.972972972972973,
 0.9784172661870504,
 0.983739837398374]

In [57]:
thresh_lst

[0.05,
 0.1,
 0.15,
 0.2,
 0.25,
 0.3,
 0.35,
 0.4,
 0.45,
 0.5,
 0.55,
 0.6,
 0.65,
 0.7,
 0.75,
 0.8,
 0.85,
 0.9,
 0.95]

In [59]:
import numpy as np
arr = np.linspace(0.01,1,40)

In [60]:
t_list = arr.tolist()
t_list

[0.01,
 0.03538461538461538,
 0.06076923076923077,
 0.08615384615384615,
 0.11153846153846153,
 0.13692307692307693,
 0.16230769230769232,
 0.18769230769230769,
 0.21307692307692308,
 0.23846153846153847,
 0.26384615384615384,
 0.28923076923076924,
 0.31461538461538463,
 0.34,
 0.36538461538461536,
 0.39076923076923076,
 0.41615384615384615,
 0.44153846153846155,
 0.46692307692307694,
 0.4923076923076923,
 0.5176923076923077,
 0.5430769230769231,
 0.5684615384615385,
 0.5938461538461538,
 0.6192307692307693,
 0.6446153846153846,
 0.67,
 0.6953846153846154,
 0.7207692307692307,
 0.7461538461538462,
 0.7715384615384615,
 0.796923076923077,
 0.8223076923076923,
 0.8476923076923076,
 0.8730769230769231,
 0.8984615384615384,
 0.9238461538461539,
 0.9492307692307692,
 0.9746153846153846,
 1.0]

In [61]:
acc_lst = []
tpr_lst = []
diff_lst = []
thresh_lst = []
for thresh in t_list:
    pred_prob = []
    pred_prob = rfc.predict_proba(X_test)
    pred_prob = (pred_prob[:,1]>=thresh).astype('int')
    cm = confusion_matrix(y_test, pred_prob)
    acc_lst.append(accuracy_score(y_test, pred_prob))
    tpr_lst.append(cm[1][1]/(cm[1][1]+cm[0][1]))
    thresh_lst.append(thresh)
    print(thresh)

0.01
0.03538461538461538
0.06076923076923077
0.08615384615384615
0.11153846153846153
0.13692307692307693
0.16230769230769232
0.18769230769230769
0.21307692307692308
0.23846153846153847
0.26384615384615384
0.28923076923076924
0.31461538461538463
0.34
0.36538461538461536
0.39076923076923076
0.41615384615384615
0.44153846153846155
0.46692307692307694
0.4923076923076923
0.5176923076923077
0.5430769230769231
0.5684615384615385
0.5938461538461538
0.6192307692307693
0.6446153846153846
0.67
0.6953846153846154
0.7207692307692307
0.7461538461538462
0.7715384615384615
0.796923076923077
0.8223076923076923
0.8476923076923076
0.8730769230769231
0.8984615384615384
0.9238461538461539
0.9492307692307692
0.9746153846153846
1.0


In [62]:
acc_lst

[0.7322905027932961,
 0.9027932960893855,
 0.9439106145251397,
 0.9582122905027933,
 0.965586592178771,
 0.9702793296089386,
 0.9731843575418995,
 0.9749720670391061,
 0.9763128491620112,
 0.9772067039106145,
 0.9789944134078212,
 0.9798882681564246,
 0.980782122905028,
 0.9812290502793296,
 0.982122905027933,
 0.9825698324022346,
 0.9832402234636871,
 0.9836871508379889,
 0.9839106145251396,
 0.9839106145251396,
 0.9841340782122905,
 0.9839106145251396,
 0.9832402234636871,
 0.9832402234636871,
 0.9832402234636871,
 0.9827932960893855,
 0.9825698324022346,
 0.9825698324022346,
 0.982122905027933,
 0.9816759776536312,
 0.9823463687150839,
 0.982122905027933,
 0.9810055865921787,
 0.9787709497206704,
 0.9774301675977654,
 0.9760893854748603,
 0.9729608938547486,
 0.9696089385474861,
 0.965586592178771,
 0.9465921787709497]

In [63]:
tpr_lst

[0.23604874919820398,
 0.461038961038961,
 0.6068965517241379,
 0.6857707509881423,
 0.7356076759061834,
 0.7713004484304933,
 0.7972027972027972,
 0.8138424821002387,
 0.8256658595641646,
 0.8353808353808354,
 0.8521303258145363,
 0.8644501278772379,
 0.8753246753246753,
 0.8798955613577023,
 0.8933333333333333,
 0.9002695417789758,
 0.907608695652174,
 0.9148351648351648,
 0.9196675900277008,
 0.9196675900277008,
 0.9269662921348315,
 0.9316239316239316,
 0.9310344827586207,
 0.9335260115606936,
 0.9411764705882353,
 0.9408284023668639,
 0.9406528189910979,
 0.9459459459459459,
 0.9483282674772037,
 0.9507692307692308,
 0.9625,
 0.9682539682539683,
 0.9707792207792207,
 0.9697986577181208,
 0.9790209790209791,
 0.9785714285714285,
 0.9774436090225563,
 0.9838056680161943,
 0.9911111111111112,
 1.0]

In [64]:
random_forest = pd.DataFrame(
    {
        'Threshold':thresh_lst,
        'Accuracy':acc_lst,
        'Sensitivity':tpr_lst
    })

In [65]:
random_forest.head()

Threshold  Accuracy  Sensitivity
0   0.010000  0.732291     0.236049
1   0.035385  0.902793     0.461039
2   0.060769  0.943911     0.606897
3   0.086154  0.958212     0.685771
4   0.111538  0.965587     0.735608

In [ ]:
random_forest['Diff']